# Generated by Django 4.2.8 on 2023-12-20 12:21

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('date_born', models.DateField(default=None, verbose_name='Birthday')),
                ('street', models.CharField(default=None, max_length=200)),
                ('city', models.CharField(default=None, max_length=400)),
                ('zipcode', models.IntegerField(default=None, validators=[users.models.validate_zipcode])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region='SI')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('social_security_number', models.CharField(default=None, max_length=13, validators=[users.models.validate_ss], verbose_name='EMŠO')),
                ('has_zpls', models.BooleanField(default=False, verbose_name='ZPLS')),
                ('has_fai', models.BooleanField(default=False, verbose_name='FAI')),
                ('antidoping_certificate', models.FileField(blank=True, max_length=300, null=True, upload_to=users.models.modify_filename, validators=[users.models.validate_file_extension])),
                ('has_valid_membership', models.BooleanField(default=False, verbose_name='valid membership')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
