# Generated by Django 4.2.8 on 2024-01-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='paid_membership',
            field=models.BooleanField(default=False, verbose_name='paid membership'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='street',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wants_valid_membership',
            field=models.BooleanField(default=False, verbose_name='wants valid membership'),
        ),
    ]
