# Generated by Django 4.2.8 on 2023-12-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='street',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
