# Generated by Django 4.2.8 on 2024-02-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.TextField(default=None, max_length=5000, verbose_name='emails')),
                ('subject', models.CharField(default=None, max_length=200, verbose_name='subject')),
                ('message', models.TextField(default=None, max_length=5000, verbose_name='message')),
            ],
        ),
    ]
