# Generated by Django 4.2.8 on 2023-12-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='paid_membership',
            field=models.BooleanField(default=False, verbose_name='paid membership'),
        ),
    ]
