# Generated by Django 4.2.8 on 2023-12-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_antidoping_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='antidoping_certificate',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='certificates/2023'),
        ),
    ]
