# Generated by Django 4.2.8 on 2023-12-20 09:47

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_antidoping_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='antidoping_certificate',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='certificates/2023/<django.db.models.fields.CharField>_<django.db.models.fields.CharField>.pdf', validators=[users.models.validate_file_extension]),
        ),
    ]
