# Generated by Django 4.2.8 on 2023-12-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_paid_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wants_valid_membership',
            field=models.BooleanField(default=False, verbose_name='wants valid membership'),
        ),
    ]
