# Generated by Django 4.2.8 on 2023-12-20 10:00

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_antidoping_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='antidoping_certificate',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to=users.models.modify_filename, validators=[users.models.validate_file_extension]),
        ),
    ]
